name: Build and Deploy

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Elige la versión de Python que estás usando

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask  # Instala Flask y otras dependencias necesarias aquí

      - name: Run Flask application to generate static files
        run: |
          flask build  # Asume que tienes un comando para generar archivos estáticos

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /app  # Ruta donde se encuentran los archivos estáticos generados

